# Text Analytics
                                                 -By Aditya Nikam(TE AI & DS)
                                                 
1.Extract Sample document and apply following document preprocessing
methods: Tokenization,POS Tagging, stop words removal, Stemming and
Lemmatization.

2.Create representation of document by calculating Term Frequency and
Inverse Document Frequency.

In [1]:
import nltk#This imports the nltk library.NLTK(Natural Language Toolkit) is a library used when we are dealing with text
#in our program.It helps in tokenization,stemming etc
nltk.download('all')#We are downloading all nltk packages here the downloading process may take 2-3 minutes
import warnings
warnings.filterwarnings('ignore')#we use this to ignore the warnings means in the output warnings should not appear

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping models\bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\book_grammars.zip.
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\brown.zip.
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\cess_esp.zip.
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\city_database.zip.
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\conll2000.zip.
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\conll2002.zip.
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\gazetteers.zip.
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\genesis.zip.
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\gutenberg.zip.
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\ieer.zip.
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\inaugural.zip.
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\indian.zip.
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\kimmo.zip.
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\mac_morpho.zip.
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping chunkers\maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping chunkers\maxent_ne_chunker_tab.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\maxent_treebank_pos_tagger_tab.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping models\moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping misc\mwa_ppdb.zip.
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\names.zip.
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\nps_chat.zip.
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\paradigms.zip.
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping misc\perluniprops.zip.
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\pil.zip.
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\pl196x.zip.
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping stemmers\porter_test.zip.
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\pros_cons.zip.
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\ptb.zip.
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping tokenizers\punkt.zip.
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping tokenizers\punkt_tab.zip.
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\qc.zip.
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping stemmers\rslp.zip.
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\sample_grammars.zip.
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\state_union.zip.
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\subjectivity.zip.
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\swadesh.zip.
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\switchboard.zip.
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping help\tagsets.zip.
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping help\tagsets_json.zip.
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\timit.zip.
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\toolbox.zip.
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\twitter_samples.zip.
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\udhr.zip.
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\verbnet3.zip.
[nltk_data]    | Downloading package webtext to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping models\wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping models\word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package wordnet2022 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\wordnet_ic.zip.
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\words.zip.
[nltk_data]    | Downloading package ycoe to
[nltk_data]    |     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

In [1]:
#Now we will perform Tokenization
from nltk.tokenize import sent_tokenize#we are importing sentence tokenization(sent_tokenize) from tokenize tool of nltk
#Sentence tokenization means if we have more than one sentences and we want to seperate out the sentences then we use 
#sentence tokenization
text="I am Bharadwaj Patil. I am third Year student of Artificial Intelligence and Data Science. Today I am performing a DSBDA practical on text analytics"
tokenized_text = sent_tokenize(text)
tokenized_text#so here in the result you will see that all three sentences are splitted this is due to sentence tokenization
#one very important thing to note that is when you are writing the text ensure that you give spacing after full stop of the
#sentence if you dont give spacing then sentence tokenizer will consider that it is one long sentence and you
#will not see the sentences splitted
#For example in:
#I am Aditya Nikam. I am third Year student of Artificial Intelligence and Data Science.
#Here if do not give spacing after full stop(Nikam. I(like this)) and directly continue the next sentence like(Nikam.I (like
#this)) then we will not get the splitted sentences all will come in one line only
#I am Aditya Nikam.I am third Year student of Artificial Intelligence and Data Science.(Here all will come in one line
#only the sentence will not be splitted as we havent gave spacing after full stop)

['I am Bharadwaj Patil.',
 'I am third Year student of Artificial Intelligence and Data Science.',
 'Today I am performing a DSBDA practical on text analytics']

In [2]:
length=len(tokenized_text)
print("Number of sentences:", length)#Here we are printing the number of sentences in the text we provided

Number of sentences: 3

In [3]:
#Now lets perform tokenization for words of sentences 
from nltk.tokenize import word_tokenize #we are importing word tokenization(word_tokenize) from tokenize tool of nltk
#Word tokenization means if we have one or more than one sentences and we want to seperate out the words then we of the 
#sentence then we use word tokenization
text="I am Bharadwaj Patil. I am third Year student of Artificial Intelligence and Data Science."
tokenized_text = word_tokenize(text)
tokenized_text#Now here in result you will see that all words of the sentences are seperated even the full stop is seperated
#Again here if you dont give spacing after full stop the word tokenizer will consider the full stop and next word as one
#complete word which is incorrect
#For example in:
#I am Aditya Nikam. I am third Year student of Artificial Intelligence and Data Science.
#Here if do not give spacing after full stop(Nikam. I(like this)) and directly continue the next word like(Nikam.I (like
#this)) then we will see that ".I" is considered as one word we dont want this we want full stop seperate and I seperate
#Like this "." "I"

['I',
 'am',
 'Bharadwaj',
 'Patil',
 '.',
 'I',
 'am',
 'third',
 'Year',
 'student',
 'of',
 'Artificial',
 'Intelligence',
 'and',
 'Data',
 'Science',
 '.']

In [4]:
length=len(tokenized_text)
print("Number of words:", length)#Here we are printing the total no of words of our text(Note that full stop is also)
#counted as word

Number of words: 17

In [9]:
#Now we want to remove the stop words from our text
from nltk.corpus import stopwords##we are importing stopwords from corpus tool of nltk
#stopwords are common English words like "is", "the", "and", etc., that are often removed from text because 
#they don’t help in data analytics
stop_words=set(stopwords.words("English"))
stop_words  
#Here we print all the stop words that are in English Language

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [8]:
text="What is your name?"
#Now I want to remove punctuation marks from my text we can do it using re(regular expression) library of python
import re#importing re(regular expression)library
text = re.sub('[^a-zA-Z]', ' ', text)#This keeps only letters in my text and replaces everything else 
#(like numbers, punctuation) with spaces.
#Note that if I write          text=re.sub('[a-zA-Z]', ' ', text) then all letters from my text will be removed and replaced
#by spaces and only letters and punctuations will remain in my text
text#You will see that punctuation mark("?") are removed here in my sentence

'What is your name '

In [6]:
#As you can see in the result of the command stop_words=set(stopwords.words("English")) which is written above all
#the stop words are in lowercase so we will first need to convert all our words of the sentence in lowercase then only 
#stopwords will be removed else not
text1="I am currently in third year of Engineering"
text1=text1.lower()#converting whole text in lowercase
tokens=word_tokenize(text1)#seperating each word from the text using word tokenize
tokens

['i', 'am', 'currently', 'in', 'third', 'year', 'of', 'engineering']

In [10]:
#Now I want to remove my stopwords 
filtered_text=[]#creating empty list to store words which are not stop words
for w in tokens:#the for loop goes through each word(w)of tokens variable
    if w not in stop_words:#this checks if the current word of loop is in the list of stop words or not.If word is not
        #a stop word then next line will execute
        #stop_words variable was decalred in above commands
        filtered_text.append(w)#this will append the word which is not stop word in filtered_text list

In [11]:
filtered_text#printing the words which are not stop words

['currently', 'third', 'year', 'engineering']

In [11]:
#Now we will do stemming

#Stemming is the process of reducing a word to its root form by removing suffixes from the word. 
#For example:
#"Running", "Runner", "Runs" → All are reduced to the base form "Run".
#"Happiness", "Happier", "Happy" → All are reduced to the base form "Happi".

from nltk.stem import PorterStemmer#Porter Stemmer is a tool which helps us to do the stemming process
porter = PorterStemmer()#created object of Porter Stemmer
print(porter.stem("Playing"))
print(porter.stem("Studies"))
print(porter.stem("Running"))
print(porter.stem("played"))
print(porter.stem("Hardworking"))
print(porter.stem("Happiness"))

play
studi
run
play
hardwork
happi

In [12]:
#Lemmatization is the process of changing a word to its base or dictionary form (called a lemma) by following proper
#grammar rules
#Stemming also converts the word in base form but the word converted by stemming may not be gramatically correct as it does
#not follow grammar rules thats the difference between stemming and lemmatization
#For example in stemming the word "studies" will be converted to "studi" which is gramtically incorrect
#But if we use lemmatization the word "studies" will be converted to "study" thats gramatically correct
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize("studies"))
print(lemmatizer.lemmatize("better"))
print(lemmatizer.lemmatize("playing"))
#Here we see that the output of playing will be playing only because lemmatize function takes the word by default as noun.
#If you do not tell the lemmatizer whether a word is a verb, noun, or adjective, 
#it will automatically assume the word is a noun.
#So as we know that playing is a verb so we should write 
print(lemmatizer.lemmatize("playing", pos="v"))#Now the output will be play
#Similarly we know that "better" is an adjective so we should write
print(lemmatizer.lemmatize("better",pos="a"))#Now the output will be good
#pos means part of speech which helps to determine whether the word is noun(n),adjective(a),or verb(v)

study
better
playing
play
good

In [13]:
#POS Tagging means  means labeling each word with correct of part of speech like whether the word is noun,verb,adjective
#adverb etc
text2 = "The white sweater fits him perfectly"
tokens1 = word_tokenize(text2)
print(nltk.pos_tag(tokens1))
#The output tells that the is Determiner(DT),white is adjective(JJ),sweater is noun(NN),fits is verb(VBZ),him is preposition
#(PRP),perfectly is adverb(RB)

[('The', 'DT'), ('white', 'JJ'), ('sweater', 'NN'), ('fits', 'VBZ'), ('him', 'PRP'), ('perfectly', 'RB')]

In [14]:
corpus = [
    'data science is one of the most important fields of science',
    'this is one of the best data science courses',
    'data scientists analyze data'
]#This creates a list of sentences and stores it in the variable corpus.
words_list = []#It Creates an empty list to store unique words only (no duplicates allowed in sets)
for doc in corpus:#The for loop goes through each sentence (doc) one by one from the corpus
    words = doc.split(' ')#Splits the sentence into words using space ' ' as the separator.
#For example 'data science' becomes ['data', 'science'].
    for word in words:#Goes through each words of the words list one by one
        if word not in words_list:#Checks if the current word is there or not in word_list if not then line executes
            words_list.append(word)#adds the current word in word_list if its not already added
print('Number of words in the corpus:', len(words_list))#Prints how many unique words are in the entire corpus.
print('The words in the corpus: \n', words_list)#Prints the actual unique words collected from all sentences.

Number of words in the corpus: 14
The words in the corpus:
 ['data', 'science', 'is', 'one', 'of', 'the', 'most', 'important', 'fields', 'this', 'best', 'courses', 'scientists', 'analyze']

In [15]:
#Term Frequency tells us how frequently(means how many times) a word has appeared in a sentence or a paragraph.
#Example:
#Imagine you have the following sentence:
#"I love programming and programming is fun."
#Here’s how you can calculate Term Frequency for the word "programming":
#The total number of words in the sentence = 7.
#The word "programming" appears 2 times.
#Term Frequency for "programming" = (Number of times "programming" appears) / (Total number of words in the document).
#So, in this case:
#TF for "programming" = 2/7 ≈ 0.29.

#The general formula of Term Frequency(TF) is

#       TF(w,d)=No.of times w has occured in the document/total numbers of words in document

#where w means word and d means document.Document means a sentence or a paragraph

#IDF(Inverse Document Frequency) formula is

#            IDF(w,d)=ln(Total number of documents in the corpus/No.of documents containing w)

#where w means word and d means document.Document means a sentence or a paragraph.corpus means just a variable where we have
#stored our sentences/paragraph.
#ln means log
#Total number of documents in the corpus means the total number of sentences in the corpus variable
#No.of documents containing w means the number of sentences where our word(w)is found

#TF-IDF is the result of the multiplication of TF and IDF

In [16]:
#Computing TF
import pandas as pd
import numpy as np
n_docs = len(corpus)#calculating the number of sentences(document) in corpus
n_words = len(words_list)#calculating the number of unique words in the corpus
df_tf = pd.DataFrame(np.zeros((n_docs, n_words)), columns=words_list)
#We create a dataframe(table) here using pd.Data Frame of size n_docs x n_words means suppose we have 3 sentences in corpus
#means n_docs=3 and no.of unique words in corpus is 14 like in our case so n_words=14
#so table will have 3 rows and 14 columns
#intially values in every column will be zero using np.zeros
#columns=words_list will make the unique words as column names means as we have 14 unique words in our example so 14 columns

for i in range(n_docs):#the for loop goes through each sentence in the corpus one by one
    words = corpus[i].split()#it seperates the words of the current sentence
    #For example: "data science is fun" becomes ["data", "science", "is", "fun"].
    for w in words:#Now we go through each word of that current sentence one by one
        df_tf.loc[i, w] += 1 /len(words)#df_tf.loc[i, w] puts the value of TF in the current row of for loop(i) and the 
        #word(w)
        #Means if for loop is running for first sentence then i value will be zero and if current word is "data" in 
        #inner for loop then df_tf.loc[i, w] will place the calculated tf value in zero row of data column using loc
        #function and same for the others
        #Here we have applied the formula of TF
        #Intially the value of numerator is kept as 1 means that word is one time if the current word appears more
        #than one time in that particular sentence then the value incremen
df_tf#df_tf prints the dataframe

#Here in the output 0 represents in row represents first sentence,1 represents second sentence and 2 represents third 
#sentence.

#If we calculate the tf for word "data" so in first sentence data appeared only once and in first sentence
#the total no of words are 11 so 1/11 comes out to be 0.090909.similarly in second sentence(first row) "data" appears once
#and the total no of word in second sentence are 9 so 1/9 comes out to be 0.111111 and similarly the word "data" in third 
#sentence appears twice and no of words in that sentence are 4 so 2/4=0.50000

#Same thing is done for other words

,data,science,is,one,of,the,most,important,fields,this,best,courses,scientists,analyze
0,0.090909,0.181818,0.090909,0.090909,0.181818,0.090909,0.090909,0.090909,0.090909,0.000000,0.000000,0.000000,0.00,0.00
1,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.000000,0.000000,0.000000,0.111111,0.111111,0.111111,0.00,0.00
2,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,0.25

In [17]:
#Computing IDF 
import numpy as np
idf_values = {}#this creates an empty dictionary to store idf values of each word

for word in words_list:#The for loop goes through each word of the set of unique words
    doc_count = 0#it will count how many sentences have the current word intially it is intialized to zero
    for doc in corpus:#This goes through each sentence of the corpus
        if word in doc.split():#doc.split() splits the sentence into words
            #if word in doc.split() checks if the current word is there or not in the sentence
            doc_count += 1#if the word is there in sentence then increase the count by 1
    idf = np.log10(n_docs / doc_count)#Applying the formula of idf
    idf_values[word] = idf# We store the calculated idf in the dictionary using the word as the key.means the word is the
    #key of the key value 
for word in sorted(idf_values.keys()):#print the idf values of each word alphabetically
    #We used sorted function()to print the words alphabetically
    print(f"{word:>10}: {idf_values[word]}")# This prints each word and its IDF score neatly aligned.
    #:>10 means the word is right-aligned in 10-character space.
    
    #For example if we take the word "data" so word data is coming in all three sentences of corpus and no of sentences
    #in corpus are also 3 so IDF=ln(3/3)=ln(1) which is equal to zero
    
    #Similarly if we take word "analyze"so word analyze is appearing only once in the three sentences and no of sentences
    #are three so IDF=ln(3/1)=ln(3)=0.477121  same thing is done for every word
    
    #Here we are taking log to the base 10 as ln so in calculator or google if you just take ln(1) or ln(3) etc then it 
    #will give different answer write "log to the base 10(3)" then our expected answer will come which is 0.477121
    #for the analyze word and same thing for other words     take log to the base 10

   analyze: 0.47712125471966244
      best: 0.47712125471966244
   courses: 0.47712125471966244
      data: 0.0
    fields: 0.47712125471966244
 important: 0.47712125471966244
        is: 0.17609125905568124
      most: 0.47712125471966244
        of: 0.17609125905568124
       one: 0.17609125905568124
   science: 0.17609125905568124
scientists: 0.47712125471966244
       the: 0.17609125905568124
      this: 0.47712125471966244

In [19]:
df_tf_idf = df_tf.copy()#we are creating a copy of df_tf dataframe to ensure that any changes made to df_tf_idf don't affect 
#the original df_tf dataframe.

# Multiply each TF value by its corresponding IDF
for word in words_list:#this starts for loop and for loop goes through each word of unique word list(word_list)which
    #is a list declared in above commands one by one
    for i in df_tf.index:#it loop through each row of our df_tf dataframe which was used to show tf values
        tf = df_tf.loc[i, word]#This line retrives value of tf for the current row and current word from df_tf dataframe
        #Like for example if currently the loop is visiting first row(row 0) of df_tf dataframe so i=0 and and if 
        #current word in for loop is "data" means w="data" then this command will retrive the zero row value of data column
        #from df_tf dataframe
        idf = idf_values[word]#it retrives the idf value of current word
        tf_idf = tf * idf#multiplying tf and idf to get tf-idf value
        df_tf_idf.loc[i, word] = tf_idf#It puts the value of TF-IDF in the current row of for loop(i) and the 
        #word(w)
        #Means if for loop is running for first row of df_tf dataframe then i value will be zero and if current word is 
        #"data" in inner for loop then df_tf_idf.loc[i, w] will place the calculated tf-idf value in zero row of data column 
        #using loc function and same for the others

# Display the TF-IDF table
df_tf_idf#printing df-tf_idf dataframe to show the values calculated

,data,science,is,one,of,the,most,important,fields,this,best,courses,scientists,analyze
0,0.0,0.032017,0.016008,0.016008,0.032017,0.016008,0.043375,0.043375,0.043375,0.000000,0.000000,0.000000,0.00000,0.00000
1,0.0,0.019566,0.019566,0.019566,0.019566,0.019566,0.000000,0.000000,0.000000,0.053013,0.053013,0.053013,0.00000,0.00000
2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.11928,0.11928